### ISSUE TITLE
Internal module from Node.Stream

### ISSUE THREAD

**Issue by jamesdbrock** [purescript-deprecated/purescript-node-streams-aff#13]
A lot of the necessary features in the __Internal__ module will soon be available available in __Node.Stream__.

https://discourse.purescript.org/t/rfc-eventemitter-bindings-and-http2-bindings/3584

https://github.com/purescript-node/purescript-node-streams/blob/update-ffi-build-on-node-event-emitters/src/Node/Stream.purs#L110-L144

**Comment by JordanMartinez** [comment]
Closing as this repo is deprecated.
