### ISSUE TITLE
Discussion for Jordan's async streams flowchart

### ISSUE THREAD

**Issue by jamesdbrock** [purescript-deprecated/purescript-node-streams-aff#8]
From https://discord.com/channels/864614189094928394/865401680497737758/1030191301423022110

![node-streams](https://user-images.githubusercontent.com/1526224/195753193-3592393a-f9f0-4552-a196-897e4c28b3be.jpg)

**Comment by jamesdbrock** [comment]
## Writeable streams

I think the current implementation covers writeable streams.

I'm not 100% certain about how it behaves for `writeStream.destroy()` or `autodestroy = true` because I haven't tested that.

## Readable streams

The current implementation only handles the `readableFlowing = false` (default) case. I read [the API](https://nodejs.org/api/stream.html#two-reading-modes) for `readableFlowing = true` and decided that it was nonsense and not worth trying to wrap in PureScript.

**Comment by JordanMartinez** [comment]
I split these up to make them easier to see individually:

![node-streams-readable](https://user-images.githubusercontent.com/8413037/195855010-bafbdbad-16ba-4eee-ad9c-6c4bcca1fab5.jpg)
![node-streams-writeable](https://user-images.githubusercontent.com/8413037/195855016-d32b72fd-4749-4735-a46d-5ed466f51049.jpg)

**Comment by jamesdbrock** [comment]
The [Node.js __Readable streams__](https://nodejs.org/docs/latest/api/stream.html#readable-streams) API documentation is one of the funniest pieces of technical writing I've ever encountered. I particularly enjoy the pathos in this paragraph.

> The `Readable` stream API evolved across multiple Node.js versions and provides multiple methods of consuming stream data. In general, developers should choose *one* of the methods of consuming data and should *never* use multiple methods to consume data from a single stream. Specifically, using a combination of `on('data')`, `on('readable')`, `pipe()`, or async iterators could lead to unintuitive behavior.

And the laughs continue further down the page when they introduce the new “Stability: 1 - Experimental” `Promise`-based API. It’s still a draft but already [comedy gold](https://twitter.com/jamesdbrock/status/1565247543503597568).

Of course this is only funny because I’ve already done the work to wrap this shambles into a single function `readSome :: Readable r -> Aff (Tuple (Array Buffer) Boolean)`. I wasn’t laughing while I was writing that function.

**Comment by JordanMartinez** [comment]
Closing as this repo is deprecated.
